### ISSUE TITLE
Hard-disable plink

### ISSUE THREAD

**Issue by QuLogic** [snoweye/pbdRPC#6]
If I pass `--disable-plink`, I expect it to be disabled. But if `ssh` and `plink` are not available, then it gets built regardless of the argument.  Instead, it should either force-disable, or error out.

**Comment by QuLogic** [comment]
Relatedly, can `plink_LICENSE` not be installed if plink is disabled?

**Comment by snoweye** [comment]
No, it has to be there. The plink should not be disabled.

**Comment by QuLogic** [comment]
Why? If you pass `--disable-plink`, you expect it to be disabled, or the build to say "Please don't do that." Just building it anyway is just going to confuse people (as I have been multiple times today because it wasn't doing what I told it to.)

If the user doesn't ask either way, then it's perfectly fine to decide automatically.

**Comment by QuLogic** [comment]
Perhaps I should provide a bit more context. I am trying to build (currently unofficial) [packages here](https://copr.fedorainfracloud.org/coprs/qulogic/IRkernel/package/R-pbdRPC/) hopefully all the way up to IRkernel. In packages, it is important to be explicit. Thus, if I tell the build not to use internal plink, I _need_ it to not do so. Blindly going forward anyway means that the package builds yet a) I've forgotten to depend on ssh and b) I've included code with a license I didn't intend.

Even though this is in the context of packaging, I don't see how this is any different as a user. If I were to pass `--disable-plink`, I'd expect it to be off or, if not possible, to _tell me it's not possible_. I don't expect it to continue on doing whatever it likes.

**Comment by snoweye** [comment]
- If a system has plink and detectable by configure, the system don't need to disable or enable it.
- If the system don't have one, then the package needs plink because that is the package for.
- Users don't need to worry about if system has one or not, don't need to worry about enable or disable, even don't need to worry about which plink is used.
- You need to change your build to install a ssh or plink or use the default before this package rather than change mine.

**Comment by QuLogic** [comment]
Those are arguments why the user doesn't _need_ to ask, but not arguments for why the build should not error if the user _explicitly disables_ plink when they shouldn't. If I try to do an impossible thing, I want to be told "no, that's impossible". The fact that I don't need to be explicit shouldn't mean I can't be explicit.

And yes, my build does install ssh, but if this package had said "No, you can't disable plink if you haven't installed ssh or plink", that would have been much clearer and I would have realized that ssh was forgotten sooner.
